const movieTitles = [
  "The Godfather",
  "The Shawshank Redemption",
  "Schindler's List",
  "Raging Bull",
  "Casablanca",
  "Citizen Kane",
  "Gone with the Wind",
  "The Wizard of Oz",
  "One Flew Over the Cuckoo's Nest",
  "Lawrence of Arabia",
  "Vertigo",
  "Psycho",
  "The Godfather Part II",
  "On the Waterfront",
  "Sunset Boulevard",
  "Forrest Gump",
  "The Sound of Music",
  "12 Angry Men",
  "West Side Story",
  "Star Wars",
  "2001: A Space Odyssey",
  "E.T. the Extra-Terrestrial",
  "The Silence of the Lambs",
  "Chinatown",
  "The Bridge on the River Kwai",
  "Singin' in the Rain",
  "It's a Wonderful Life",
  "Dr. Strangelove",
  "Some Like It Hot",
  "Ben-Hur",
  "Apocalypse Now",
  "Amadeus",
  "Gladiator",
  "Titanic",
  "Saving Private Ryan",
  "The Green Mile",
  "The Pianist",
  "Braveheart",
  "The Departed",
  "Inception",
  "Goodfellas",
  "Pulp Fiction",
  "Fight Club",
  "The Matrix",
  "The Lord of the Rings: The Fellowship of the Ring",
  "The Lord of the Rings: The Two Towers",
  "The Lord of the Rings: The Return of the King",
  "Back to the Future",
  "Raiders of the Lost Ark",
  "The Lion King",
  "Jurassic Park",
  "The Terminator",
  "Terminator 2: Judgment Day",
  "Alien",
  "Aliens",
  "Blade Runner",
  "A Clockwork Orange",
  "Full Metal Jacket",
  "The Shining",
  "Platoon",
  "Jaws",
  "Rocky",
  "The Exorcist",
  "Taxi Driver",
  "Good Will Hunting",
  "Rain Man",
  "American Beauty",
  "Glory",
  "Dances with Wolves",
  "A Beautiful Mind",
  "Slumdog Millionaire",
  "The King's Speech",
  "Argo",
  "Django Unchained",
  "The Wolf of Wall Street",
  "Mad Max: Fury Road",
  "La La Land",
  "The Revenant",
  "Whiplash",
  "The Social Network",
  "The Dark Knight",
  "The Dark Knight Rises",
  "Avengers: Infinity War",
  "Avengers: Endgame",
  "Black Panther",
  "Spider-Man: Into the Spider-Verse",
  "Toy Story",
  "Toy Story 3",
  "Finding Nemo",
  "Up",
  "WALL-E",
  "Inside Out",
  "Coco",
  "The Incredibles",
  "Shrek",
  "Frozen",
  "Beauty and the Beast",
  "Aladdin",
  "Mulan",
  "Moana",
  "Zootopia",
  "The Little Mermaid",
  "Snow White and the Seven Dwarfs",
];

module.exports = movieTitles;
